allowBuilds:
  '@parcel/watcher': true
  esbuild: true
  vue-demi: true
patchedDependencies:
  '@xterm/addon-search@0.17.0-beta.301': patches/@xterm__addon-search@0.17.0-beta.301.patch
  '@xterm/xterm@6.1.0-beta.304': patches/@xterm__xterm@6.1.0-beta.304.patch
