import {
  ClipboardCopy,
  ClipboardPaste,
  Copy,
  Download,
  Eraser,
  FilePenLine,
  FilePlus,
  FolderOpen,
  FolderPlus,
  ListChecks,
  RefreshCw,
  RotateCcw,
  RotateCw,
  Scissors,
  Search,
  Terminal,
  TextSelect,
  Trash2,
  Upload,
} from "@lucide/vue";

const ICONS = {
  clear: Eraser,
  copy: Copy,
  copyPath: ClipboardCopy,
  cut: Scissors,
  delete: Trash2,
  download: Download,
  edit: FilePenLine,
  newFile: FilePlus,
  newFolder: FolderPlus,
  open: FolderOpen,
  paste: ClipboardPaste,
  redo: RotateCw,
  refresh: RefreshCw,
  rename: FilePenLine,
  search: Search,
  selectAll: TextSelect,
  terminal: Terminal,
  terminalSelectAll: ListChecks,
  undo: RotateCcw,
  upload: Upload,
};

const DEFAULT_ICON_BY_ID = {
  "global-copy": "copy",
  "global-cut": "cut",
  "global-delete": "delete",
  "global-paste": "paste",
  "global-redo": "redo",
  "global-select-all": "selectAll",
  "global-undo": "undo",
  "relationship-edit": "edit",
  "relationship-focus-related": "search",
  "relationship-quick-add": "redo",
  "relationship-refresh": "refresh",
  "relationship-delete-credential": "delete",
  "relationship-remove-relation": "delete",
  "sftp-copy-path": "copyPath",
  "sftp-delete": "delete",
  "sftp-download": "download",
  "sftp-edit": "edit",
  "sftp-new-file": "newFile",
  "sftp-new-folder": "newFolder",
  "sftp-open": "open",
  "sftp-refresh": "refresh",
  "sftp-rename": "rename",
  "sftp-select-all": "selectAll",
  "sftp-upload": "upload",
  "terminal-clear": "clear",
  "terminal-search": "search",
  "terminal-select-all": "terminalSelectAll",
};

/** 右键菜单项的图标解析。 */
export function contextMenuIconFor(item) {
  return ICONS[item?.icon || DEFAULT_ICON_BY_ID[item?.id] || "terminal"] || Terminal;
}
